version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/http-foundation
    versions:
    - 4.4.18
  - dependency-name: filp/whoops
    versions:
    - 2.9.1
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
